"""Add app_state table

Revision ID: 2f529bd5172b
Revises: a94ff349e82d
Create Date: 2026-04-14 23:14:18.384273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f529bd5172b'
down_revision: Union[str, None] = 'a94ff349e82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_app_state_key'), 'app_state', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_state_key'), table_name='app_state')
    op.drop_table('app_state')
    # ### end Alembic commands ###
